### PR TITLE
Starting the Spanish translation

### PR DESCRIPTION
**Pull request by Weeesly**

### CODE REVIEW

**Review by realeatham — CHANGES_REQUESTED** [review]
update /public/locales/es/index.ts to include es-419

**Review by realeatham — APPROVED** [review]

**Review by Abhinav5383 — CHANGES_REQUESTED** [review]
You should not include region name in the locale name,
see the [Translation guide](https://github.com/CRModders/cosmic-mod-manager/blob/main/public/locales/GUIDE.md)

**Comment by Abhinav5383** [comment]
The locales have been updated, a lot more keys are added now.
The spanish locale is ai generated so you can create a new translation for spanish. I have added a guide in the locales folder also

**Comment by Abhinav5383** [comment]
Closing the PR due to no response.

**Pull request closed without merging**
