### PR TITLE
Create index.ts For Norwegien

### PR DESCRIPTION
**Pull request by maralnor**
Tried to make an index following the English. Making Bokmål the default language, even if it is just a version of the same language that should really be equal to Nynorsk.

### CODE REVIEW

**Comment by maralnor** [comment]
Also tried to make this part of my previus pull request, but failed. Working on combining them.

**Comment by realeatham** [comment]
> Also tried to make this part of my previus pull request, but failed. Working on combining them.

they are from differnt branches in your fork, that is the problem

**Comment by realeatham** [comment]
1 PR per branch and 1 branch per PR

**Comment by realeatham** [comment]
can i close this? #14 has this file in it

**Pull request closed without merging**
